# Generated by Django 5.0.6 on 2024-06-27 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewRealm', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero_Juego',
            fields=[
                ('id_genero_juego', models.AutoField(db_column='idGeneroJuego', primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='id_genero',
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('desarrollador', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('plataforma', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('clasificacion', models.CharField(max_length=200)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='media/portadas/')),
                ('id_genero_juego', models.ForeignKey(db_column='idGeneroJuego', on_delete=django.db.models.deletion.CASCADE, to='ReviewRealm.genero_juego')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
