# Generated by Django 5.0.6 on 2024-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewRealm', '0003_genero_juego_remove_jugador_id_genero_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
