# Generated by Django 5.0.6 on 2024-06-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewRealm', '0004_alter_juego_imagen_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='id',
        ),
        migrations.AddField(
            model_name='juego',
            name='id_juego',
            field=models.AutoField(db_column='idJuego', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
